#! /bin/sh

BASE_URL="https://xlayerrpc.okx.com"

methods=(
    "blockNumber"
    "getBlockByNumber"
    "getBlockByHash"
    "getBlockTransactionCountByNumber"
    "getBlockTransactionCountByHash"
    "getTransactionByHash"
    "getTransactionByBlockHashAndIndex"
    "getTransactionByBlockNumberAndIndex"
    "getRawTransactionByBlockNumberAndIndex"
    "getRawTransactionByBlockHashAndIndex"
    "getRawTransactionByHash"
    "getTransactionReceipt"
    "getLogs"
    "getBlockReceipts"
    "getUncleByBlockNumberAndIndex"
    "getUncleByBlockHashAndIndex"
    "getUncleCountByBlockNumber"
    "getUncleCountByBlockHash"
    "newPendingTransactionFilter"
    "newBlockFilter"
    "newFilter"
    "uninstallFilter"
    "getFilterChanges"
    "getFilterLogs"
    "accounts"
    "getBalance"
    "getTransactionCount"
    "getStorageAt"
    "getCode"
    "blockNumber"
    "syncing"
    "chainId"
    "protocolVersion"
    "gasPrice"
)

for method in "${methods[@]}"
do
    method_name="$method"
    #wrk -t 16 -c 5000 -d 60s -T 30s -s "$method_name.lua" "$BASE_URL"
    wrk -t 2 -c 10 -d 10s -T 10s -s "$method_name.lua" "$BASE_URL"
    printf "\n"
done